#!/usr/bin/env bash
# =============================================================================
# AI Agent Orchestrator — Interactive Setup Script
# Run with: bash scripts/setup.sh
# =============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}${BOLD}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}${BOLD}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}${BOLD}[WARN]${NC} $*"; }
error()   { echo -e "${RED}${BOLD}[ERR]${NC}  $*" >&2; }

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
ENV_EXAMPLE="$PROJECT_ROOT/.env.example"

echo ""
echo -e "${BOLD}============================================${NC}"
echo -e "${BOLD}  AI Agent Orchestrator — Setup Wizard     ${NC}"
echo -e "${BOLD}============================================${NC}"
echo ""

# ---------------------------------------------------------------------------
# 1. Check prerequisites
# ---------------------------------------------------------------------------
info "Checking prerequisites..."

MISSING=0
for cmd in docker curl; do
    if ! command -v "$cmd" &>/dev/null; then
        error "'$cmd' is not installed. Please install it and re-run this script."
        MISSING=1
    fi
done

if ! docker compose version &>/dev/null 2>&1; then
    error "'docker compose' (v2) is not available. Please upgrade Docker Desktop or install the Compose plugin."
    MISSING=1
fi

[[ $MISSING -eq 1 ]] && exit 1
success "Docker and Docker Compose are available."
echo ""

# ---------------------------------------------------------------------------
# 2. Choose LLM provider
# ---------------------------------------------------------------------------
echo -e "${BOLD}Which LLM provider do you want to use?${NC}"
echo "  1) AWS Bedrock   (recommended — uses Claude 3.5 Sonnet)"
echo "  2) OpenAI        (GPT-4o)"
echo "  3) Ollama        (local/self-hosted — free, no API key required)"
echo ""
read -rp "Enter choice [1-3]: " PROVIDER_CHOICE

case "$PROVIDER_CHOICE" in
    1) LLM_PROVIDER="bedrock" ;;
    2) LLM_PROVIDER="openai" ;;
    3) LLM_PROVIDER="ollama" ;;
    *) error "Invalid choice. Exiting."; exit 1 ;;
esac
echo ""

# ---------------------------------------------------------------------------
# 3. Collect provider-specific credentials
# ---------------------------------------------------------------------------
AWS_REGION="us-east-1"
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
LLM_MODEL=""
OPENAI_API_KEY=""
OPENAI_MODEL="gpt-4o"
OLLAMA_BASE_URL="http://localhost:11434"
OLLAMA_MODEL="llama3.2"

if [[ "$LLM_PROVIDER" == "bedrock" ]]; then
    read -rp "AWS Region [$AWS_REGION]: " input
    AWS_REGION="${input:-$AWS_REGION}"
    read -rp "AWS Access Key ID: " AWS_ACCESS_KEY_ID
    read -rsp "AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
    echo ""
    LLM_MODEL="anthropic.claude-3-5-sonnet-20241022-v2:0"
    read -rp "Bedrock Model ID [$LLM_MODEL]: " input
    LLM_MODEL="${input:-$LLM_MODEL}"

elif [[ "$LLM_PROVIDER" == "openai" ]]; then
    read -rp "OpenAI API Key: " OPENAI_API_KEY
    read -rp "OpenAI Model [$OPENAI_MODEL]: " input
    OPENAI_MODEL="${input:-$OPENAI_MODEL}"

elif [[ "$LLM_PROVIDER" == "ollama" ]]; then
    warn "Make sure Ollama is running and the model is pulled before starting the container."
    warn "  ollama pull $OLLAMA_MODEL"
    echo ""
    read -rp "Ollama base URL [$OLLAMA_BASE_URL]: " input
    OLLAMA_BASE_URL="${input:-$OLLAMA_BASE_URL}"
    read -rp "Ollama model [$OLLAMA_MODEL]: " input
    OLLAMA_MODEL="${input:-$OLLAMA_MODEL}"
fi

# ---------------------------------------------------------------------------
# 4. API security
# ---------------------------------------------------------------------------
echo ""
API_KEY="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 32 || true)"
if [[ -z "$API_KEY" ]]; then
    API_KEY="change-me-$(date +%s)"
fi
echo -e "${BOLD}API Key (save this — you'll need it for all API requests):${NC}"
echo -e "  ${GREEN}$API_KEY${NC}"
echo ""

# ---------------------------------------------------------------------------
# 5. Write .env file
# ---------------------------------------------------------------------------
info "Writing $ENV_FILE ..."
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

LLM_PROVIDER=$LLM_PROVIDER

# AWS Bedrock
AWS_REGION=$AWS_REGION
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
LLM_MODEL=$LLM_MODEL

# OpenAI
OPENAI_API_KEY=$OPENAI_API_KEY
OPENAI_MODEL=$OPENAI_MODEL

# Ollama
OLLAMA_BASE_URL=$OLLAMA_BASE_URL
OLLAMA_MODEL=$OLLAMA_MODEL

# API Security
API_KEY=$API_KEY
REQUIRE_API_KEY=true
WEBHOOK_SECRET=

# Application
DEBUG=false
LOG_LEVEL=INFO
HOST=0.0.0.0
PORT=8000
EOF
success ".env file written."
echo ""

# ---------------------------------------------------------------------------
# 6. Start the stack
# ---------------------------------------------------------------------------
echo -e "${BOLD}Start the orchestrator now?${NC}"
read -rp "  [Y/n]: " START_NOW
START_NOW="${START_NOW:-Y}"

if [[ "${START_NOW^^}" == "Y" ]]; then
    info "Building and starting Docker containers..."
    cd "$PROJECT_ROOT"
    docker compose up -d --build
    echo ""
    # Wait for health check
    info "Waiting for service to become healthy..."
    RETRIES=18
    for i in $(seq 1 $RETRIES); do
        STATUS=$(docker inspect --format='{{.State.Health.Status}}' ai-agent-orchestrator 2>/dev/null || echo "starting")
        if [[ "$STATUS" == "healthy" ]]; then
            break
        fi
        echo -n "."
        sleep 5
    done
    echo ""
    STATUS=$(docker inspect --format='{{.State.Health.Status}}' ai-agent-orchestrator 2>/dev/null || echo "unknown")
    if [[ "$STATUS" == "healthy" ]]; then
        success "Service is healthy!"
    else
        warn "Service health status: $STATUS — check logs with: docker compose logs -f"
    fi
    echo ""
    echo -e "${BOLD}============================================${NC}"
    echo -e "${BOLD}  Setup complete!                           ${NC}"
    echo -e "${BOLD}============================================${NC}"
    echo ""
    echo -e "  API URL:    ${GREEN}http://localhost:8000${NC}"
    echo -e "  Docs:       ${GREEN}http://localhost:8000/docs${NC}"
    echo -e "  API Key:    ${GREEN}$API_KEY${NC}"
    echo ""
    echo -e "  Test with:"
    echo -e "    ${CYAN}curl -H 'X-API-Key: $API_KEY' http://localhost:8000/api/v1/health${NC}"
    echo ""
    echo -e "  View logs:"
    echo -e "    ${CYAN}docker compose logs -f${NC}"
    echo ""
else
    echo ""
    info "Skipping startup. Run when ready:"
    echo -e "  ${CYAN}docker compose up -d --build${NC}"
    echo ""
fi
